import { SimpleProduct } from "./page";

export const MOCKS: SimpleProduct[] = [
  {
    "id": "02ad5dd8-c0e9-4c00-b1e7-6b203185e35c",
    "name": "Mitre Shell",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/mitre_shell.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Prehistoric mitre shells measured 20 cubits in length, and were covered in shaggy fur."
  },
  {
    "id": "030b38b0-1bea-4d86-a7dc-21819259c795",
    "name": "Ham",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Meats/ham.png",
    "eaten_raw": false,
    "hunger": 50,
    "bladder": -11,
    "energy": 7,
    "category": "Meats",
    "description": "There are countless way to prepare a succulent ham: spiced, diced, and even baked in a radiant glaze of glory."
  },
  {
    "id": "03d8a784-d2f4-46db-883f-8a7754f1c6a4",
    "name": "Soap Plant",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/soap_plant.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "If it wasn't for this one miracle plant, your hygiene would be yet another unfortunate casualty of the shipwreck."
  },
  {
    "id": "07f6a342-ba20-4088-8497-f0eff5ec539b",
    "name": "Shark Leather",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/shark_leather.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Sharks were once docile, good humored animals until people started making shoes out of them."
  },
  {
    "id": "090bfe08-7006-4b50-93f1-2c6b1a2c802c",
    "name": "Freshwater Eel",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Meats/freshwater_eel.png",
    "eaten_raw": false,
    "hunger": 28,
    "bladder": -10,
    "energy": 11,
    "category": "Meats",
    "description": "Don't let its freshwater innocence fool you, this anguilliformes comes from a house of eel repute."
  },
  {
    "id": "099481da-426d-45fb-a874-6a14f924ce9c",
    "name": "Alien Food",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Meats/alien_food.png",
    "eaten_raw": false,
    "hunger": 53,
    "bladder": -6,
    "energy": 15,
    "category": "Meats",
    "description": "Colonels Yylarg's Gourmet Space Slurry. Now with 20% more Blarg Mjark!"
  },
  {
    "id": "0a738754-6e07-4e0c-99fd-359529d842e1",
    "name": "Ti Leaves",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/ti_leaves.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Ti Leaves have been traditionally used as part of clothing creation and decoration."
  },
  {
    "id": "0b0c0ab6-451f-4dd7-81eb-1d6969ee5661",
    "name": "Purple Orchid",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/purple_orchid.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Only the most virile bees dare attempt to pollinate the voluptuous purple orchid."
  },
  {
    "id": "0b2ffed0-35d4-4617-8335-66202d93f21b",
    "name": "Egg",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Meats/egg.png",
    "eaten_raw": false,
    "hunger": 26,
    "bladder": -5,
    "energy": 5,
    "category": "Meats",
    "description": "The noble egg. Fruit of a chicken's posterior."
  },
  {
    "id": "0d9aabc6-b150-4485-b848-89d8cd6e1422",
    "name": "Moonstone",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/moonstone.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Moonstone appear in a multitude of colors, none of which look like the moon."
  },
  {
    "id": "0e53b47c-8d25-4136-b325-203f64db89e2",
    "name": "Kingfish",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/MediumFishes/kingfish.png",
    "eaten_raw": false,
    "hunger": 35,
    "bladder": -10,
    "energy": 10,
    "category": "Medium Fishes",
    "description": "The kingfish is king in name only, but still rules what he can with an iron fin."
  },
  {
    "id": "118d12fd-bcfc-4475-a7bf-fde27daad436",
    "name": "Hardwood",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/hardwood.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "This resilient wood is the ultimate in both style and durability for crafting."
  },
  {
    "id": "13048730-abb5-4ccb-9f08-3ed678b438da",
    "name": "Mangosteen",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Fruits/mangosteen.png",
    "eaten_raw": true,
    "hunger": 31,
    "bladder": -4,
    "energy": 9,
    "category": "Fruits",
    "description": "Nothing is more refreshing than a cold grass of mangosteenade."
  },
  {
    "id": "138c4a77-9f76-42cf-8776-228646af1631",
    "name": "Honeycomb",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Spices/honeycomb.png",
    "eaten_raw": false,
    "hunger": 7,
    "bladder": -4,
    "energy": 14,
    "category": "Spices",
    "description": "Honeycombs are labyrinths of tiny spaces, not unlike an office full of cubicles."
  },
  {
    "id": "185fa46a-9ec1-4dd6-b1ec-e032db420bdc",
    "name": "Blood Orange",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Fruits/blood_orange.png",
    "eaten_raw": true,
    "hunger": 28,
    "bladder": -4,
    "energy": 4,
    "category": "Fruits",
    "description": "Caution: Gorging on blood oranges may result in a crime scene of hemorrhaged crimson juices."
  },
  {
    "id": "1c611f3c-f985-4053-b9f6-c10474694a71",
    "name": "Barracuda",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/MediumFishes/barracuda.png",
    "eaten_raw": false,
    "hunger": 24,
    "bladder": -7,
    "energy": 10,
    "category": "Medium Fishes",
    "description": "Barracuda mate for life, or at least until domething better swims along."
  },
  {
    "id": "1cd42047-076d-49c1-94bd-97ce5b388b4f",
    "name": "Black Carp",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/SmallFishes/black_carp.png",
    "eaten_raw": false,
    "hunger": 16,
    "bladder": -4,
    "energy": 5,
    "category": "Small Fishes",
    "description": "Get inside this fish's mind to truly understand the world according to carp."
  },
  {
    "id": "1d59144e-1fe0-4f53-9332-d6977d036c51",
    "name": "Cotton",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/cotton.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Its soft absorbency makes cotton an ideal fabric for delicates and unmentionables."
  },
  {
    "id": "1e669568-ef1e-4aa4-9ead-afcc6e2c14cf",
    "name": "Nautilus Shell",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/nautilus_shell.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Primitive island cultures often used shells as money. To this day, there are some island where two \"nauts\" will still buy you a shrimp and pepper gyro."
  },
  {
    "id": "1eb5576f-6a8e-47d5-bf32-b9a11cd88262",
    "name": "Black Rockfish",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/MediumFishes/black_rockfish.png",
    "eaten_raw": false,
    "hunger": 25,
    "bladder": -7,
    "energy": 7,
    "category": "Medium Fishes",
    "description": "Black rockfish often eat their young, or die trying."
  },
  {
    "id": "21697bbd-4cd7-4d8f-856f-e8a52f0ef32f",
    "name": "Red Dye",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/red_dye.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Red is the color of rage and war, or yummy strawberries, depending on your mood."
  },
  {
    "id": "22345423-1324-4cf1-86c6-f7907b62af7d",
    "name": "Manchineel Fruit",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/manchineel_fruit.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "The manchineel tree is entirely poisonous, including its fruit, bark, and leaves. Treat with extreme caution."
  },
  {
    "id": "24cb86d6-344b-4abf-9e39-f7c8b67a1d0a",
    "name": "Leather",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/leather.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "Boar leather may seem a bit \"renaissance faire\", but its practical uses are too many to ignore."
  },
  {
    "id": "265663eb-a072-4e6f-9354-4206916804e3",
    "name": "Moonfish",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/LargeFishes/moonfish.png",
    "eaten_raw": false,
    "hunger": 52,
    "bladder": -8,
    "energy": 12,
    "category": "Large Fishes",
    "description": "After a long day of hiding under rocks, the night belongs to moonfish."
  },
  {
    "id": "283f7b97-7aa5-4261-8bf1-86a21e9fb6c3",
    "name": "Lemon",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Fruits/lemon.png",
    "eaten_raw": true,
    "hunger": 22,
    "bladder": -3,
    "energy": 6,
    "category": "Fruits",
    "description": "A lemon day keeps scurvy away, which means you will need to find another way to make money."
  },
  {
    "id": "2b78da3f-3948-4841-892e-5097132dd958",
    "name": "Cannonball Fruit",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Resources/cannonball_fruit.png",
    "eaten_raw": false,
    "hunger": 0,
    "bladder": 0,
    "energy": 0,
    "category": "Resources",
    "description": "The perfurmed fragrance of this tree's flowers belie the poisonous nature of its toxic fruit."
  },
  {
    "id": "2bf448f6-afb9-46fa-b2d3-849ddf9cb07c",
    "name": "Chilipepper",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/SmallFishes/chilipepper.png",
    "eaten_raw": false,
    "hunger": 16,
    "bladder": -7,
    "energy": 9,
    "category": "Small Fishes",
    "description": "The chilipepper is spectacularly ugly fish with a large underbite and tiny, unimpressive fins."
  },
  {
    "id": "2c7fa6a1-9c8e-466a-bb09-857c7c920689",
    "name": "Dolphin-Fish",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/MediumFishes/dolphin-fish.png",
    "eaten_raw": false,
    "hunger": 34,
    "bladder": -9,
    "energy": 9,
    "category": "Medium Fishes",
    "description": "With an average IQ of over 185, even the dumbest dolphin-fish is much smarter than you."
  },
  {
    "id": "2d1ff120-a250-4511-b422-325310740e49",
    "name": "Yam",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/VeggiesNutsandGrains/yam.png",
    "eaten_raw": true,
    "hunger": 31,
    "bladder": -5,
    "energy": 0,
    "category": "Veggies, Nuts, and Grains",
    "description": "Shamans of some cultures imbue yams with magical properties, others imbue it wih butter and brown sugar."
  },
  {
    "id": "3035af00-56a1-4998-be1f-67a779641227",
    "name": "Sugar Cane",
    "image": "https://raw.githubusercontent.com/apify-apps/apify-static-assets/master/TheSims/CastawayProducts/Spices/sugar_cane.png",
    "eaten_raw": false,
    "hunger": 6,
    "bladder": -3,
    "energy": 15,
    "category": "Spices",
    "description": "\"No cane, no gain\" is a way of life for those who swear by an all-sugar diet."
  }
]